const KEY = 'trialsutra_trials_v1';
const demoTrials = [
  {id:'demo-diabetes',name:'Comparative Study of Ayurvedic Intervention in Type 2 Diabetes',pi:'Dr. Meera Nair',site:'AIIA, New Delhi',target:120,enrolled:41,status:'Active',ethics:'Approved',ctri:'Registered',safety:1,milestone:'Interim review · 15 Oct'},
  {id:'demo-osteo',name:'Ayurvedic Protocol for Knee Osteoarthritis',pi:'Dr. R. K. Sharma',site:'AIIA, New Delhi',target:80,enrolled:56,status:'Active',ethics:'Approved',ctri:'Registered',safety:0,milestone:'Follow-up completion · 03 Nov'},
  {id:'demo-pcos',name:'Integrated Ayurveda Care in PCOS',pi:'Dr. Anjali Verma',site:'CCRAS, Jaipur',target:100,enrolled:18,status:'Active',ethics:'Approved',ctri:'Pending',safety:0,milestone:'Site recruitment review · 08 Oct'}
];
const $ = s => document.querySelector(s);
function trials(){try{const saved=JSON.parse(localStorage.getItem(KEY));return Array.isArray(saved)?saved:demoTrials}catch{return demoTrials}}
function save(data){localStorage.setItem(KEY,JSON.stringify(data))}
function pct(t){return t.target ? Math.min(100,Math.round((Number(t.enrolled)/Number(t.target))*100)) : 0}
function lag(t){return t.status==='Active' && pct(t)<50}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function badge(s){return `<span class="badge ${s.toLowerCase()}">${esc(s)}</span>`}
function layout(content, active='Dashboard') { return `<div class="shell"><aside class="side"><div class="brand"><div class="brand-mark">✚</div><span>TrialSutra<small>Clinical Intelligence</small></span></div><nav class="nav">${[['Dashboard','▦','#/dashboard'],['Trials','▤','#/trials'],['Recruitment','◔','#/recruitment'],['Data Monitoring','◌','#/monitoring'],['Pharmacovigilance','♢','#/safety'],['Ethics & CTRI','✓','#/ethics'],['Alerts','⚠','#/alerts'],['Reports','▱','#/reports']].map(x=>`<a class="${active===x[0]?'active':''}" href="${x[2]}"><span class="icon">${x[1]}</span><span>${x[0]}</span></a>`).join('')}</nav><div class="demo-user"><strong>Demo Researcher</strong>AIIA Clinical Research Unit</div></aside><main class="main">${content}</main></div>` }
function pageHeader(title,sub,action=''){return `<div class="topbar"><div><div class="eyebrow">TrialSutra · Demo workspace</div><h1>${title}</h1>${sub?`<div class="sub">${sub}</div>`:''}</div>${action}</div>`}
function trialRow(t){const p=pct(t);return `<tr><td><div class="trial-name" onclick="location.hash='#/trial/${t.id}'">${esc(t.name)}</div><div class="sub">${esc(t.pi)}</div></td><td>${esc(t.site)}</td><td>${badge(t.status)}</td><td><div class="progress-wrap"><div class="progress-label">${t.enrolled} / ${t.target} · ${p}%</div><div class="progress ${lag(t)?'low':''}"><i style="width:${p}%"></i></div></div></td><td>${badge(t.ethics)}</td><td>${badge(t.ctri)}</td></tr>`}
function dashboard(){const data=trials(), active=data.filter(t=>t.status==='Active'), enrolled=data.reduce((n,t)=>n+Number(t.enrolled),0), avg=data.length?Math.round(data.reduce((n,t)=>n+pct(t),0)/data.length):0, alerts=data.filter(lag);return layout(pageHeader('Research command centre','Track trials, enrolment and compliance at a glance.',`<button class="button" onclick="location.hash='#/create'">+ Create Trial</button>`)+`<section class="metrics"><div class="card metric"><div class="metric-label">ACTIVE TRIALS</div><div class="metric-value">${active.length}</div><div class="metric-note">Across ${new Set(data.map(t=>t.site)).size} research sites</div></div><div class="card metric"><div class="metric-label">TOTAL PARTICIPANTS</div><div class="metric-value">${enrolled}</div><div class="metric-note">Currently enrolled</div></div><div class="card metric"><div class="metric-label">RECRUITMENT PROGRESS</div><div class="metric-value">${avg}%</div><div class="metric-note">Portfolio average</div></div><div class="card metric"><div class="metric-label">PENDING ACTIONS</div><div class="metric-value">${alerts.length}</div><div class="metric-note ${alerts.length?'alert':''}">${alerts.length?'Recruitment needs attention':'No recruitment concerns'}</div></div></section>${alerts.length?`<div class="alert-strip"><span>⚠</span><div><strong>Recruitment attention required</strong><span>${alerts.length} active trial${alerts.length>1?'s are':' is'} below the expected recruitment milestone.</span></div><button class="button text" onclick="location.hash='#/alerts'">View alerts →</button></div>`:''}<div class="section-head"><div><h2>Recent & active trials</h2><p>Demo data is provided for presentation purposes.</p></div><button class="button secondary" onclick="location.hash='#/trials'">View all trials</button></div><div class="card table-card"><table class="trial-table"><thead><tr><th>Trial & investigator</th><th>Site</th><th>Status</th><th>Recruitment</th><th>Ethics</th><th>CTRI</th></tr></thead><tbody>${data.slice(0,5).map(trialRow).join('')}</tbody></table></div>`,'Dashboard')}
function create(){return layout(pageHeader('Create a trial','Add the essential study details. You can monitor it immediately after saving.')+`<div class="card form-card"><h2>Trial details</h2><p>Fields marked required are needed to create the trial.</p><form id="trial-form"><div class="form-grid"><div class="field full"><label>Trial Name *</label><input required name="name" placeholder="e.g. Ayurvedic Intervention in Type 2 Diabetes"></div><div class="field"><label>Principal Investigator *</label><input required name="pi" placeholder="Dr. Name"></div><div class="field"><label>Study Site *</label><input required name="site" placeholder="e.g. AIIA, New Delhi"></div><div class="field"><label>Target Participants *</label><input required min="1" type="number" name="target" placeholder="120"></div><div class="field"><label>Current Enrolment *</label><input required min="0" type="number" name="enrolled" value="0" placeholder="0"></div><div class="field"><label>Trial Status *</label><select name="status"><option>Active</option><option>Planning</option><option>On Hold</option><option>Completed</option></select></div><div class="field"><label>Ethics Approval Status *</label><select name="ethics"><option>Approved</option><option>Pending</option><option>Review</option></select></div><div class="field"><label>CTRI Registration Status *</label><select name="ctri"><option>Registered</option><option>Pending</option><option>Not Started</option></select></div></div><div id="form-error" class="error"></div><div class="form-actions"><button type="button" class="button secondary" onclick="location.hash='#/dashboard'">Cancel</button><button class="button" type="submit">Create Trial</button></div></form></div>`,'Trials')}
function details(id){const t=trials().find(x=>x.id===id);if(!t)return layout(pageHeader('Trial not found','This trial may no longer be available.')+`<button class="button" onclick="location.hash='#/dashboard'">Back to dashboard</button>`,'Trials');const p=pct(t);return layout(`<span class="back" onclick="location.hash='#/dashboard'">← Back to dashboard</span>`+pageHeader(t.name,`${t.site} · Principal Investigator: ${t.pi}`)+`${lag(t)?`<div class="alert-strip"><span>⚠</span><div><strong>Recruitment Lag Detected</strong><span>Current recruitment is below the expected milestone. Review site recruitment activity.</span></div></div>`:''}<div class="details-grid"><div class="card detail-card"><h2>Trial overview</h2><div class="detail-list"><div><span class="detail-label">PRINCIPAL INVESTIGATOR</span><div class="detail-value">${esc(t.pi)}</div></div><div><span class="detail-label">STUDY SITE</span><div class="detail-value">${esc(t.site)}</div></div><div><span class="detail-label">TRIAL STATUS</span>${badge(t.status)}</div><div><span class="detail-label">ETHICS STATUS</span>${badge(t.ethics)}</div><div><span class="detail-label">CTRI STATUS</span>${badge(t.ctri)}</div></div></div><div class="card detail-card"><h2>Recruitment progress</h2><div style="font:800 30px Manrope">${p}%</div><div class="sub" style="margin:3px 0 11px">${t.enrolled} of ${t.target} target participants</div><div class="progress ${lag(t)?'low':''}" style="height:9px"><i style="width:${p}%"></i></div></div><div class="card detail-card"><h2>Key metrics</h2><div class="kpi"><span>Target participants</span><b>${t.target}</b></div><div class="kpi"><span>Enrolled participants</span><b>${t.enrolled}</b></div><div class="kpi"><span>Recruitment rate</span><b>${p}%</b></div><div class="kpi"><span>Safety events</span><b>${t.safety ?? 0}</b></div><div class="kpi"><span>Next milestone</span><b>${esc(t.milestone||'Initial site review')}</b></div></div><div class="card detail-card"><h2>Monitoring note</h2><p style="color:var(--muted);line-height:1.6;margin:0">${lag(t)?'Recruitment trend requires site-level follow-up before the next milestone.':'✓ Recruitment Progress On Track'}</p></div></div>`,'Trials')}
function list(){return layout(pageHeader('Trials','All studies in your demo workspace.',`<button class="button" onclick="location.hash='#/create'">+ Create Trial</button>`)+`<div class="card table-card"><table class="trial-table"><thead><tr><th>Trial & investigator</th><th>Site</th><th>Status</th><th>Recruitment</th><th>Ethics</th><th>CTRI</th></tr></thead><tbody>${trials().map(trialRow).join('')}</tbody></table></div>`,'Trials')}
function alerts(){const data=trials().filter(lag);return layout(pageHeader('Recruitment alerts','Rule-based monitoring flags trials below 50% recruitment progress.')+`${data.length?data.map(t=>`<div class="card detail-card" style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;gap:12px"><div><div class="eyebrow" style="color:var(--red)">Recruitment Lag Detected</div><h2 style="margin:6px 0">${esc(t.name)}</h2><p style="color:var(--muted);margin:0">Current recruitment is ${pct(t)}% (${t.enrolled} of ${t.target}), below the expected milestone.</p></div><button class="button secondary" onclick="location.hash='#/trial/${t.id}'">Open trial</button></div></div>`).join(''):`<div class="card empty">No recruitment lag alerts right now.</div>`}`,'Alerts')}
function placeholder(type,icon,text,cards){return layout(pageHeader(type,'Prototype module for the next phase of TrialSutra.')+`<div class="card placeholder"><div class="placeholder-icon">${icon}</div><h2>${type}</h2><p>${text}</p><div class="mini-cards">${cards.map(c=>`<div class="mini-card">${c[0]}<span>${c[1]}</span></div>`).join('')}</div></div>`,type)}
function render(){const route=location.hash||'#/dashboard';let page;if(route==='#/dashboard')page=dashboard();else if(route==='#/create')page=create();else if(route==='#/trials')page=list();else if(route.startsWith('#/trial/'))page=details(route.split('/')[2]);else if(route==='#/alerts')page=alerts();else if(route==='#/recruitment')page=placeholder('Recruitment','◔','Site-level enrolment trends and screening funnels will be available here.',[['Screened','Future module'],['Site performance','Future module']]);else if(route==='#/monitoring')page=placeholder('Data Monitoring','◌','Data-quality review and monitoring visit summaries will be available here.',[['Queries open','Future module'],['Monitoring visits','Future module']]);else if(route==='#/safety')page=placeholder('Pharmacovigilance','♢','A concise safety-monitoring workspace for adverse events and serious adverse events.',[['AE count','Future module'],['SAE count','Future module']]);else if(route==='#/ethics')page=placeholder('Ethics & CTRI','✓','Centralised approval and registration tracking will be available here.',[['Approval status','Future module'],['Compliance action','Future module']]);else if(route==='#/reports')page=placeholder('Reports','▱','Reports & CDISC export — coming in the next phase.',[['Portfolio summary','Future module'],['CDISC export','Next phase']]);else page=dashboard();$('#app').innerHTML=page;if(route==='#/create')$('#trial-form').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(+f.enrolled>+f.target){$('#form-error').textContent='Current enrolment cannot be greater than the target participants.';return}const t={...f,id:'trial-'+Date.now(),target:+f.target,enrolled:+f.enrolled,safety:0,milestone:'Initial site review'};const all=trials();all.unshift(t);save(all);location.hash='#/trial/'+t.id})}
function demoLogin(){return `<div class="login-page"><section class="login-card"><div class="brand"><div class="brand-mark">✚</div><span>TrialSutra<small>Clinical Intelligence</small></span></div><div class="eyebrow">AIIA Clinical Research Unit</div><h1>Welcome to TrialSutra</h1><p>Intelligent Clinical Trial Management &amp; Monitoring Platform for a focused, demonstration-ready research workspace.</p><div class="demo-note"><strong>Demonstration environment</strong><br>Use demo access to explore sample studies and create a trial.</div><button class="button" onclick="enterDemo()">Enter Demo Workspace</button><div class="login-foot">No patient data is used in this MVP.</div></section></div>`}
function enterDemo(){localStorage.setItem('trialsutra_demo_access_v1','true');location.hash='#/dashboard';boot()}
function boot(){if(localStorage.getItem('trialsutra_demo_access_v1')!=='true'){$('#app').innerHTML=demoLogin();return}render()}
window.addEventListener('hashchange',boot);boot();
